{"name": "Попытка принять заказ с неверным ID курьера", "status": "passed", "attachments": [{"name": "stdout", "source": "2642db99-7418-4d1c-b25f-1ffe8f149e85-attachment.txt", "type": "text/plain"}], "start": 1734602235237, "stop": 1734602236948, "uuid": "e41ad79f-5d38-4d1b-81b3-d4f0c352ff10", "historyId": "55dfccba666be633f9cae552dee1b4c6", "testCaseId": "55dfccba666be633f9cae552dee1b4c6", "fullName": "tests.orders.accept_order.test_accept_order_invalid_courier_id.TestAcceptOrderInvalidCourierId#test_accept_order_invalid_courier_id", "labels": [{"name": "feature", "value": "Принятие заказа"}, {"name": "parentSuite", "value": "tests.orders.accept_order"}, {"name": "suite", "value": "test_accept_order_invalid_courier_id"}, {"name": "subSuite", "value": "TestAcceptOrderInvalidCourierId"}, {"name": "host", "value": "MBP-Dmitrij.lan"}, {"name": "thread", "value": "5388-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.orders.accept_order.test_accept_order_invalid_courier_id"}]}