{"name": "Запрос с несуществующим номером заказа возвращает ошибку", "status": "passed", "start": 1734240722881, "stop": 1734240723686, "uuid": "28788293-28b7-4f29-a268-e78cfc6fafb2", "historyId": "ae1f0b89719aefe7a0f703deb4c0bbdd", "testCaseId": "ae1f0b89719aefe7a0f703deb4c0bbdd", "fullName": "tests.orders.test_get_order_by_track_nonexistent_number.TestGetOrderByTrackNonexistentNumber#test_get_order_by_track_nonexistent_number", "labels": [{"name": "feature", "value": "Получение заказа по несуществующему номеру"}, {"name": "parentSuite", "value": "tests.orders"}, {"name": "suite", "value": "test_get_order_by_track_nonexistent_number"}, {"name": "subSuite", "value": "TestGetOrderByTrackNonexistentNumber"}, {"name": "host", "value": "MBP-Dmitrij.lan"}, {"name": "thread", "value": "2644-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.orders.test_get_order_by_track_nonexistent_number"}]}