{"name": "Запрос с несуществующим номером заказа возвращает ошибку", "status": "passed", "start": 1734159613433, "stop": 1734159614419, "uuid": "157940e1-b886-4503-8675-98a92e99aadb", "historyId": "ae1f0b89719aefe7a0f703deb4c0bbdd", "testCaseId": "ae1f0b89719aefe7a0f703deb4c0bbdd", "fullName": "tests.orders.test_get_order_by_track_nonexistent_number.TestGetOrderByTrackNonexistentNumber#test_get_order_by_track_nonexistent_number", "labels": [{"name": "feature", "value": "Получение заказа по несуществующему номеру"}, {"name": "parentSuite", "value": "tests.orders"}, {"name": "suite", "value": "test_get_order_by_track_nonexistent_number"}, {"name": "subSuite", "value": "TestGetOrderByTrackNonexistentNumber"}, {"name": "host", "value": "MBP-Dmitrij.lan"}, {"name": "thread", "value": "6210-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.orders.test_get_order_by_track_nonexistent_number"}]}